---
abstract: 'translate Getopt::Long specs into a hash of attributes, and back again'
author:
  - 'Stephen R. Scaffidi <sscaffidi@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Long-Spec
requires:
  Carp: 0
  Data::Dumper: 0
  strict: 0
  warnings: 0
version: 0.001
